### PR TITLE
Corrected Footer Information

### PR DESCRIPTION
**Pull request by PhrydRhys**
Pull request refers to [Issue #5](https://github.com/joannakl/cs480_s18/issues/5)  

@rchau0623 Please help me verify if this fix is adequate

### CODE REVIEW

**Comment by ryanchau** [comment]
Hi @PhrydRhys, please update the anchor tag as well as the name. The link is as follows: https://www.nyu.edu/registrar/calendars/university-academic-calendar.html#1184

**Comment by PhrydRhys** [comment]
I'm not sure if the anchor tag is for this issue; I think that is for #23. However, if the tag is considered part of the issue, I can work on updating the URL.

**Comment by joannakl** [comment]
this should be fixed in this issue - as this was mentioned in the discussion part of the issue reported

**Comment by PhrydRhys** [comment]
I was unsure on how to edit my previous pull request, so I made a new one: #57 

**EDIT**: Never mind, I JUST learned how to edit my previous pull request.
@rchau0623 Please help me verify if this new fix of the URL anchor is adequate or not

**Comment by joannakl** [comment]
@rchau0623 please verify that this is not correct

**Comment by ryanchau** [comment]
This looks good to me.

**Pull request merged**
