### PR TITLE
Fixed paren issue on textbooks page - Second Try

### PR DESCRIPTION
**Pull request by rosaswaby**
Fixed the missing parenthesis on the textbooks page. Reference to issue here:(#34 (comment)) - Original PR #55 did not merge

### CODE REVIEW

**Comment by rosaswaby** [comment]
Working on the first pull request! #55

**Comment by rosaswaby** [comment]
fixed merge conflict

**Comment by joannakl** [comment]
@rosaswaby  well, there seen to be new merge conflicts now - several issues related to _config.yml file have been resolved today and  I guess some of them conflict with this file. Please take a look again.

**Comment by joannakl** [comment]
This is now fine, but this issue was fixed by #55.

**Pull request closed without merging**
