### PR TITLE
Issue #17: Fix the no recitation problem in the how to get help.

### PR DESCRIPTION
**Pull request by wentaozou1**

### CODE REVIEW

**Comment by joannakl** [comment]
@dayo-adebanjo  you need to verify and approve this fix to issue #17

**Comment by dayo-adebanjo** [comment]
looks good, thanks!

**Comment by joannakl** [comment]
This change does not comply with what was discussed in the issue #17 that it claims to solve.

**Comment by dayo-adebanjo** [comment]
@wentaozou1 please remove the comment "also, you can ask your classmates about the questions"

**Comment by wentaozou1** [comment]
I have changed the it

**Comment by dayo-adebanjo** [comment]
thanks! issue #17 should now be solved

**Pull request merged**
