### PR TITLE
Added config properties for tutor name and hours.

### PR DESCRIPTION
**Pull request by jhelfgot1**
added content to index.markdown to display these properties.

### CODE REVIEW

**Comment by S1MB10T3** [comment]
Ran this locally on my machine. Fixes mentioned works.

**Comment by joannakl** [comment]
There is no mention of which issue this is supposed to be fixing.

**Comment by jhelfgot1** [comment]
Here is a link to the issue: https://github.com/joannakl/cs480_s18/issues/45

Sorry for the delay

**Comment by wentaozou1** [comment]
I think the solution is all good. It should be merged.

**Pull request merged**
