### PR TITLE
fixed header so that piazza button links correctly

### PR DESCRIPTION
**Pull request by dmckenna24**
The button to GitHub page lead us to Piazza, so I changed the text on the site to say Piazza rather than GitHub.

### CODE REVIEW

**Comment by S1MB10T3** [comment]
The text on the button and the link match up but now there's no github link in the navbar.

**Comment by joannakl** [comment]
The github link is part of another issue - I think. If not, it can be reported after this is merged.

@dmckenna24 the merge conflict needs to be resolved before this can be merged.

**Comment by dmckenna24** [comment]
Now there are links for both the GitHub and Piazza links, with the merge conflict corrected.

**Comment by joannakl** [comment]
there is no mention of the issue number that this is fixing.

**Pull request merged**
